# <center>**SmartInternz Project**</center>  
### <center>Amazon Kindle Store Analysis</center>
  
  
**Submitted by:-**  
* Aditya Deepak Joshi 19BCE0257 *(adityadeepak.joshi2019@vitstudent.ac.in)*  
* Abhinav Gorantla 19BCE0241    *(abhinav.gorantla2019@vitstudent.ac.in)*  
* V L Rishi 19BCE7553    *(rishi.19bce7553@vitap.ac.in)*  
* Atharva Ramgirkar 19BCE0114 *(atharva.ramgirkar2019@vitstudent.ac.in)* 




---


## <center> Table of Content</center>  
1. Importing Libraries  
  1.1 Download Dependencies  
  1.2 Initialize Objects  
2. Reading the Dataset
3. Looking at the Data  
  3.1 Handling Null Values
4. Data Preprocessing  
  4.1 Deleting Unnecessary Columns  
  4.2 Combining Columns  
  4.3 Encoding Target Column  
  4.4 Text Preprocessing  
5. Read Data Final Dataset  
6. Balance the Dataset  
7. Define Target and Predictor Variables  
8. Vectorize the Text  
9. Train Test Split  
10. Buliding The Model  
  10.1 Adding Input Layer  
  10.2 Adding Hidden Layers  
  10.3 Adding Output Layer  
  10.4 Compiling the Model  
  10.5 Training the Model  
11. Single Predictions  
12. Saving the Model  
13. Testing the Saved Model  
  13.1 Loading the Saved Model  
  13.2 Prediction Using the Saved Model  
  







---



#### 1. Importing Libraries

In [16]:
import pandas as pd
import numpy as np

# For Text Preprocessing
import nltk
from nltk.corpus import stopwords
import re
## Stemming
from nltk.stem.porter import PorterStemmer
## Lemmatization
from nltk.stem import WordNetLemmatizer
## Bag of Words Model
from sklearn.feature_extraction.text import CountVectorizer

# For Checking Directories
import os

# To Slpit Data into Train and Test
from sklearn.model_selection import train_test_split

# For Neural Network
import tensorflow
import keras
## For Sequential Model
from tensorflow.keras.models import Sequential
## To Add Layers
from tensorflow.keras.layers import Dense

# To Save the Model
from keras.models import load_model

# To Pickle Objects
import pickle

##### 1.1 Download Dependencies

In [2]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

##### 1.2 Initialize Objects

In [4]:
ps = PorterStemmer()
wordnet = WordNetLemmatizer()
cv = CountVectorizer(max_features=5000)
model=Sequential()

#### 2. Reading the Dataset

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/SmartInternz_Project/Data/kindle_reviews.csv")

#### 3. Looking at the Data

In [ ]:
df

In [ ]:
df.head()

Unnamed: 0        asin  ...             summary  unixReviewTime
0           0  B000F83SZQ  ...  Nice vintage story      1399248000
1           1  B000F83SZQ  ...        Different...      1388966400
2           2  B000F83SZQ  ...               Oldie      1396569600
3           3  B000F83SZQ  ...  I really liked it.      1392768000
4           4  B000F83SZQ  ...      Period Mystery      1395187200

[5 rows x 10 columns]

In [ ]:
df.tail()

Unnamed: 0  ... unixReviewTime
982614      982614  ...     1406073600
982615      982615  ...     1406073600
982616      982616  ...     1406073600
982617      982617  ...     1406073600
982618      982618  ...     1406073600

[5 rows x 10 columns]

In [ ]:
df.describe()

Unnamed: 0        overall  unixReviewTime
count  982619.000000  982619.000000    9.826190e+05
mean   491309.000000       4.347801    1.378183e+09
std    283657.816416       0.955056    2.298476e+07
min         0.000000       1.000000    9.522144e+08
25%    245654.500000       4.000000    1.365206e+09
50%    491309.000000       5.000000    1.383523e+09
75%    736963.500000       5.000000    1.396051e+09
max    982618.000000       5.000000    1.406074e+09

##### 3.1 Handling Null Values

In [ ]:
df.isnull().sum()

Unnamed: 0           0
asin                 0
helpful              0
overall              0
reviewText          22
reviewTime           0
reviewerID           0
reviewerName      3816
summary              1
unixReviewTime       0
dtype: int64

In [ ]:
df.isnull().any()

Unnamed: 0        False
asin              False
helpful           False
overall           False
reviewText         True
reviewTime        False
reviewerID        False
reviewerName       True
summary            True
unixReviewTime    False
dtype: bool

In [ ]:
df = df.dropna(axis=0,how="any")

In [ ]:
df.isnull().any()

Unnamed: 0        False
asin              False
helpful           False
overall           False
reviewText        False
reviewTime        False
reviewerID        False
reviewerName      False
summary           False
unixReviewTime    False
dtype: bool

In [ ]:
df.reset_index(drop=True,inplace=True)

In [ ]:
df.tail()

Unnamed: 0  ... unixReviewTime
978775      982614  ...     1406073600
978776      982615  ...     1406073600
978777      982616  ...     1406073600
978778      982617  ...     1406073600
978779      982618  ...     1406073600

[5 rows x 10 columns]

In [ ]:
df.shape

(978780, 10)

#### 4. Data Preprocessing

##### 4.1 Deleting Unnecessary Columns

In [ ]:
del df['asin']
del df['Unnamed: 0']
del df['helpful']
del df['reviewTime']
del df['reviewerID']
del df['reviewerName']
del df['unixReviewTime']

In [ ]:
df.columns

Index(['overall', 'reviewText', 'summary'], dtype='object')

##### 4.2 Combining Columns

In [ ]:
df['reviewText'] = df['reviewText'] + " " + df['summary']

In [ ]:
df.head()

overall  ...             summary
0        5  ...  Nice vintage story
1        4  ...        Different...
2        4  ...               Oldie
3        5  ...  I really liked it.
4        4  ...      Period Mystery

[5 rows x 3 columns]

In [ ]:
df['reviewText'][0]

"I enjoy vintage books and movies so I enjoyed reading this book.  The plot was unusual.  Don't think killing someone in self-defense but leaving the scene and the body without notifying the police or hitting someone in the jaw to knock them out would wash today.Still it was a good read for me. Nice vintage story"

In [ ]:
df.drop(['summary'],axis=1,inplace=True)

In [ ]:
df.head()

overall                                         reviewText
0        5  I enjoy vintage books and movies so I enjoyed ...
1        4  This book is a reissue of an old one; the auth...
2        4  This was a fairly interesting read.  It had ol...
3        5  I'd never read any of the Amy Brewster mysteri...
4        4  If you like period pieces - clothing, lingo, y...

In [ ]:
df.isna().sum()

overall       0
reviewText    0
summary       0
dtype: int64

##### 4.3 Encoding Target Column  
* **0** *for Positive Review*  
* **1** *for Negative Review* 

In [ ]:
df['overall']=np.where(df['overall']>=3,0,1)

In [ ]:
df.overall.value_counts()

0    922034
1     56746
Name: overall, dtype: int64

##### 4.4 Text Preprocessing

In [ ]:
corpus=[]
for i in range(len(X)):

  # Removing Special Characters
  temp = re.sub('[^a-zA-Z]',' ',X[i])

  # Converting to Lower Case
  temp = temp.lower()

  # SPliting Sentences to List of Words
  temp = temp.split()

  # Removing Stop Words and Lemmatizaion
  temp = [wordnet.lemmatize(word) for word in temp if not word in set(stopwords.words('english'))]
  
  # Reforming the Sentence
  temp = ' '.join(temp)

  # Appending to Corpus
  corpus.append(temp)

In [ ]:
len(corpus)

978780

In [ ]:
corpus[0]

'enjoy vintage book movie enjoyed reading book plot unusual think killing someone self defense leaving scene body without notifying police hitting someone jaw knock would wash today still good read nice vintage story'

#### 5. Read Data Final Dataset

In [5]:
final_reviews = pd.read_csv("/content/drive/MyDrive/SmartInternz_Project/Data/final_reviews.csv")

In [6]:
final_reviews

Unnamed: 0                                                  0  overall
0                0  enjoy vintage book movie enjoyed reading book ...        0
1                1  book reissue old one author born era say nero ...        0
2                2  fairly interesting read old style terminology ...        0
3                3  never read amy brewster mystery one really hoo...        0
4                4  like period piece clothing lingo enjoy mystery...        0
...            ...                                                ...      ...
978775      978775  yasss hunny great read dre mess cherika refuse...        0
978776      978776  enjoyed book beginning end far lex hoe sneaky ...        0
978777      978777  great book cherika fool let man get away much ...        0
978778      978778  say excellent book please believe definitely p...        0
978779      978779  book everything hope alexus wise move lawd tho...        0

[978780 rows x 3 columns]

#### 6. Balance the Dataset

In [7]:
final_reviews1 = final_reviews[final_reviews['overall']==1]

In [8]:
final_reviews1.shape

(56746, 3)

In [9]:
final_reviews0 = final_reviews[final_reviews['overall']==0]

In [10]:
final_reviews0

Unnamed: 0                                                  0  overall
0                0  enjoy vintage book movie enjoyed reading book ...        0
1                1  book reissue old one author born era say nero ...        0
2                2  fairly interesting read old style terminology ...        0
3                3  never read amy brewster mystery one really hoo...        0
4                4  like period piece clothing lingo enjoy mystery...        0
...            ...                                                ...      ...
978775      978775  yasss hunny great read dre mess cherika refuse...        0
978776      978776  enjoyed book beginning end far lex hoe sneaky ...        0
978777      978777  great book cherika fool let man get away much ...        0
978778      978778  say excellent book please believe definitely p...        0
978779      978779  book everything hope alexus wise move lawd tho...        0

[922034 rows x 3 columns]

In [11]:
df = pd.concat([final_reviews1,final_reviews0[0:56764]])

In [ ]:
df

Unnamed: 0                                                  0  overall
21             21  ylesia novella originally published e book for...        1
39             39  whatever reason star war short story bit hit m...        1
42             42  admit snapped moment saw new release tend anyt...        1
64             64  english accent seemed trying hide know impress...        1
65             65  somewhat disappointment article missed pepper ...        1
...           ...                                                ...      ...
62813       62813  third installment ongoing trinity saga memory ...        0
62814       62814  finished book looking forward series admit boo...        0
62815       62815  taking one star error book otherwise throughly...        0
62817       62817  must say whole time reading kept thinking one ...        0
62818       62818  put book entertained making u think thing may ...        0

[113510 rows x 3 columns]

In [12]:
df.reset_index(drop=True,inplace=True)

In [13]:
df

Unnamed: 0                                                  0  overall
0               21  ylesia novella originally published e book for...        1
1               39  whatever reason star war short story bit hit m...        1
2               42  admit snapped moment saw new release tend anyt...        1
3               64  english accent seemed trying hide know impress...        1
4               65  somewhat disappointment article missed pepper ...        1
...            ...                                                ...      ...
113505       62813  third installment ongoing trinity saga memory ...        0
113506       62814  finished book looking forward series admit boo...        0
113507       62815  taking one star error book otherwise throughly...        0
113508       62817  must say whole time reading kept thinking one ...        0
113509       62818  put book entertained making u think thing may ...        0

[113510 rows x 3 columns]

#### 7. Define Target and Predictor Variables 

In [14]:
y = df['overall'].values
X = list(df['0'].values)

In [ ]:
X

In [ ]:
X[0]

'ylesia novella originally published e book form walter jon williams get opportunity insert story novel destiny way event ylesia take place midway book good read tackle immediately finishing destiny way novella follows new republic mission titular planet serving capital traitorous peace brigade house attempt senate peace brigade promote capitulation yuuzhan vong served human counterpoint effort jedi heroic member new republic throughout new jedi order logical part story one found terribly interesting rarely get anything told point view making rather cardboard adversary yleisa brings back thracken sal solo entertaining plotline see forcibly installed president peace brigade fit well sal solo plan better galactic situation display knack adaption survival unlike famous cousin han solo ylesia major source drug spice star war galaxy familiar reader c crispin han solo trilogy nice see return part yleisa advance story destiny way much primarily delivers closure peace brigade subplot sal solo 

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 0])

#### 8. Vectorize the Text

In [15]:
X = cv.fit_transform(X).toarray()

In [17]:
pickle.dump(cv, open('cv.pkl', 'wb'))

#### 9. Train Test Split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=4,stratify=y)

#### 10. Buliding The Model

##### 10.1 Adding Input Layer 

In [ ]:
model.add(Dense(input_dim=5000,kernel_initializer="random_uniform",activation="relu",units=5000))

##### 10.2 Adding Hidden Layers

In [ ]:
model.add(Dense(units=3000,kernel_initializer="random_uniform",activation="relu"))

In [ ]:
model.add(Dense(units=1000,kernel_initializer="random_uniform",activation="relu"))

##### 10.3 Adding Output Layer

In [ ]:
model.add(Dense(units=1,kernel_initializer="random_uniform",activation="sigmoid"))

##### 10.4 Compiling the Model

In [ ]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

##### 10.5 Training the Model

In [ ]:
model.fit(X_train,y_train,epochs=2,batch_size=32,validation_data=(X_test,y_test))

Epoch 1/2
2484/2484 [==============================] - 757s 304ms/step - loss: 0.3145 - accuracy: 0.8750 - val_loss: 0.2822 - val_accuracy: 0.8854
Epoch 2/2
2484/2484 [==============================] - 752s 303ms/step - loss: 0.1940 - accuracy: 0.9252 - val_loss: 0.3147 - val_accuracy: 0.8853


#### 11. Single Predictions

In [ ]:
model.predict(cv.transform(['book is amazing']))

array([[0.02651107]], dtype=float32)

#### 12. Saving the Model

In [ ]:
model.save('nlp_model.h5')

#### 13. Testing the Saved Model

##### 13.1 Loading the Saved Model

In [20]:
nlp_model = load_model('/content/drive/MyDrive/SmartInternz_Project/model/nlp_model.h5')

In [22]:
cv_saved = cv=pickle.load(open('/content/drive/MyDrive/SmartInternz_Project/model/cv.pkl','rb'))

##### 13.2 Prediction Using the Saved Model

In [ ]:
nlp_model.predict(cv.transform(['book is amazing']))

array([[0.02651107]], dtype=float32)

In [23]:
nlp_model.predict(cv_saved.transform(['book is amazing']))

array([[0.02651107]], dtype=float32)

The Answer is near 0, so the review is Predicted Positive. Thus, it is a correct Prediction

In [ ]:
nlp_model.predict(cv.transform(['i did not like this book. Not good. Poor . Waste of time']))

array([[0.9753436]], dtype=float32)

The Answer is near 1, so the review is Predicted Negative. Thus, it is a correct Prediction



---


